module DemoApiScalarGalaxy
  module Models
    type celestial_body_create_params =
      { celestial_body: DemoApiScalarGalaxy::Models::celestial_body }
      & DemoApiScalarGalaxy::Internal::Type::request_parameters

    class CelestialBodyCreateParams < DemoApiScalarGalaxy::Internal::Type::BaseModel
      extend DemoApiScalarGalaxy::Internal::Type::RequestParameters::Converter
      include DemoApiScalarGalaxy::Internal::Type::RequestParameters

      attr_accessor celestial_body: DemoApiScalarGalaxy::Models::celestial_body

      def initialize: (
        celestial_body: DemoApiScalarGalaxy::Models::celestial_body,
        ?request_options: DemoApiScalarGalaxy::request_opts
      ) -> void

      def to_hash: -> {
        celestial_body: DemoApiScalarGalaxy::Models::celestial_body,
        request_options: DemoApiScalarGalaxy::RequestOptions
      }
    end
  end
end
