module DemoApiScalarGalaxy
  module Models
    type webhook_unwrap_params =
      {  } & DemoApiScalarGalaxy::Internal::Type::request_parameters

    class WebhookUnwrapParams < DemoApiScalarGalaxy::Internal::Type::BaseModel
      extend DemoApiScalarGalaxy::Internal::Type::RequestParameters::Converter
      include DemoApiScalarGalaxy::Internal::Type::RequestParameters

      def initialize: (
        ?request_options: DemoApiScalarGalaxy::request_opts
      ) -> void

      def to_hash: -> { request_options: DemoApiScalarGalaxy::RequestOptions }
    end
  end
end
